export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const CLEAR_VALUES = 'CLEAR_VALUES';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const DISPLAY_FORM = 'DISPLAY_FORM';
export const ADD_QUERY = 'ADD_QUERY';

export const CREATE_INVOICE_BEGIN = 'CREATE_INVOICE_BEGIN';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR';

export const ADD_INVOICE_ITEM = 'ADD_INVOICE_ITEM';
export const CHANGE_INVOICE_ITEM = 'CHANGE_INVOICE_ITEM';
export const DELETE_INVOICE_ITEM = 'DELETE_INVOICE_ITEM';

export const GET_INVOICES_BEGIN = 'GET_INVOICES_BEGIN';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';

export const GET_SINGLE_INVOICE_BEGIN = 'GET_SINGLE_INVOICE_BEGIN';
export const GET_SINGLE_INVOICE_SUCCESS = 'GET_SINGLE_INVOICE_SUCCESS';
export const GET_SINGLE_INVOICE_ERROR = 'GET_SINGLE_INVOICE_ERROR';

export const SET_EDIT_INVOICE = 'SET_EDIT_INVOICE';
export const SET_DELETE_INVOICE = 'SET_DELETE_INVOICE';

export const EDIT_INVOICE_BEGIN = 'EDIT_INVOICE_BEGIN';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_ERROR = 'EDIT_INVOICE_ERROR';

export const CHANGE_INVOICE_STATUS_BEGIN = 'CHANGE_INVOICE_STATUS_BEGIN';
export const CHANGE_INVOICE_STATUS_SUCCESS = 'CHANGE_INVOICE_STATUS_SUCCESS';
export const CHANGE_INVOICE_STATUS_ERROR = 'CHANGE_INVOICE_STATUS_ERROR';

export const DELETE_INVOICE_BEGIN = 'DELETE_INVOICE_BEGIN';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_ERROR = 'DELETE_INVOICE_ERROR';
